services:
  - type: web
    name: backend-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ConnectionStrings__Connection
        value: Host=dpg-cvntrejuibrs73aee630-a.oregon-postgres.render.com;Port=5432;Database=dinamiccitasapp;Username=dinamiccitasapp_user;Password=4r72Z6zOrd7BjugIHbQSwLCfMwUNuwnI;Ssl Mode=Require;Trust Server Certificate=true
